2025-06-22 13:41:10,788 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 13:41:10] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 13:43:22,969 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/Logger/Log.py', reloading
2025-06-22 13:44:15,233 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 13:44:15] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 13:45:43,746 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/Logger/Log.py', reloading
2025-06-22 13:46:34,455 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 13:46:34] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 13:47:05,753 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/Logger/Log.py', reloading
2025-06-22 13:47:08,480 - root - ERROR => 'Select' object has no attribute 'password'
'Select' object has no attribute 'password'
2025-06-22 13:47:08,480 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 13:47:08] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 13:57:30,531 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/routes/auth.py', reloading
2025-06-22 13:57:33,315 - root - ERROR => 'Select' object has no attribute 'password'
'Select' object has no attribute 'password'
2025-06-22 13:57:33,315 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 13:57:33] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 13:58:35,712 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/routes/auth.py', reloading
2025-06-22 14:00:32,196 - root - ERROR => (psycopg2.OperationalError) connection to server at "0.0.0.0", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
(psycopg2.OperationalError) connection to server at "0.0.0.0", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-22 14:00:32,197 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:00:32] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 14:02:03,242 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/routes/auth.py', reloading
2025-06-22 14:08:49,964 - root - ERROR => (psycopg2.OperationalError) connection to server at "0.0.0.0", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
(psycopg2.OperationalError) connection to server at "0.0.0.0", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-22 14:08:49,965 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:08:49] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 14:09:17,607 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/Logger/Log.py', reloading
2025-06-22 14:09:24,492 - root - ERROR => (psycopg2.OperationalError) connection to server at "0.0.0.0", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
(psycopg2.OperationalError) connection to server at "0.0.0.0", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-22 14:09:24,493 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:09:24] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 14:10:33,449 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/routes/auth.py', reloading
2025-06-22 14:10:34,871 - root - ERROR => (psycopg2.OperationalError) connection to server at "0.0.0.0", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
(psycopg2.OperationalError) connection to server at "0.0.0.0", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-22 14:10:34,872 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:10:34] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 14:11:44,280 - root - ERROR => No row was found when one was required
No row was found when one was required
2025-06-22 14:11:44,281 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:11:44] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 14:13:22,289 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/Repository/UserRepository.py', reloading
2025-06-22 14:13:25,144 - root - ERROR => No row was found when one was required
No row was found when one was required
2025-06-22 14:13:25,145 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:13:25] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 14:14:39,656 - root - ERROR => No row was found when one was required
No row was found when one was required
2025-06-22 14:14:39,657 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:14:39] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 14:15:02,236 - root - ERROR => No row was found when one was required
No row was found when one was required
2025-06-22 14:15:02,236 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:15:02] "[35m[1mPOST /api/v1/auth/login HTTP/1.1[0m" 500 -
2025-06-22 14:18:11,990 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:18:11] "OPTIONS /api/v1/plan HTTP/1.1" 200 -
2025-06-22 14:18:12,006 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:18:12] "GET /api/v1/plan HTTP/1.1" 200 -
2025-06-22 14:19:21,435 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:19:21] "OPTIONS /api/v1/auth/register HTTP/1.1" 200 -
2025-06-22 14:19:21,445 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:19:21] "[31m[1mPOST /api/v1/auth/register HTTP/1.1[0m" 400 -
2025-06-22 14:21:17,094 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/routes/auth.py', reloading
2025-06-22 14:21:22,155 - root - ERROR => list index out of range
list index out of range
2025-06-22 14:21:22,156 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:21:22] "[35m[1mPOST /api/v1/auth/register HTTP/1.1[0m" 500 -
2025-06-22 14:24:13,571 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/routes/auth.py', reloading
2025-06-22 14:24:38,137 - root - ERROR => (psycopg2.errors.UndefinedColumn) column "business_name" of relation "business" does not exist
LINE 1: INSERT INTO business (business_name, business_address, busin...
                              ^

[SQL: INSERT INTO business (business_name, business_address, business_phone, owner_id, payment_frequency, start_service) VALUES (%(business_name)s, %(business_address)s, %(business_phone)s, %(owner_id)s, %(payment_frequency)s, %(start_service)s) RETURNING business.id]
[parameters: {'business_name': 'laspdev', 'business_address': 'calle 7 # 55-109', 'business_phone': '3209345419', 'owner_id': 1, 'payment_frequency': None, 'start_service': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
(psycopg2.errors.UndefinedColumn) column "business_name" of relation "business" does not exist
LINE 1: INSERT INTO business (business_name, business_address, busin...
                              ^

[SQL: INSERT INTO business (business_name, business_address, business_phone, owner_id, payment_frequency, start_service) VALUES (%(business_name)s, %(business_address)s, %(business_phone)s, %(owner_id)s, %(payment_frequency)s, %(start_service)s) RETURNING business.id]
[parameters: {'business_name': 'laspdev', 'business_address': 'calle 7 # 55-109', 'business_phone': '3209345419', 'owner_id': 1, 'payment_frequency': None, 'start_service': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-22 14:24:38,138 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:24:38] "[35m[1mPOST /api/v1/auth/register HTTP/1.1[0m" 500 -
2025-06-22 14:28:04,048 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:28:04] "OPTIONS /api/v1/auth/register HTTP/1.1" 200 -
2025-06-22 14:28:04,095 - root - ERROR => (psycopg2.errors.UndefinedColumn) column "start_service" of relation "business" does not exist
LINE 1: ...ess, business_phone, owner_id, payment_frequency, start_serv...
                                                             ^

[SQL: INSERT INTO business (business_name, business_address, business_phone, owner_id, payment_frequency, start_service) VALUES (%(business_name)s, %(business_address)s, %(business_phone)s, %(owner_id)s, %(payment_frequency)s, %(start_service)s) RETURNING business.id]
[parameters: {'business_name': 'laspdev', 'business_address': 'calle 7 # 55-109', 'business_phone': '3209345419', 'owner_id': 2, 'payment_frequency': None, 'start_service': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
(psycopg2.errors.UndefinedColumn) column "start_service" of relation "business" does not exist
LINE 1: ...ess, business_phone, owner_id, payment_frequency, start_serv...
                                                             ^

[SQL: INSERT INTO business (business_name, business_address, business_phone, owner_id, payment_frequency, start_service) VALUES (%(business_name)s, %(business_address)s, %(business_phone)s, %(owner_id)s, %(payment_frequency)s, %(start_service)s) RETURNING business.id]
[parameters: {'business_name': 'laspdev', 'business_address': 'calle 7 # 55-109', 'business_phone': '3209345419', 'owner_id': 2, 'payment_frequency': None, 'start_service': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-22 14:28:04,095 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:28:04] "[35m[1mPOST /api/v1/auth/register HTTP/1.1[0m" 500 -
2025-06-22 14:29:19,013 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/database/models/Business.py', reloading
2025-06-22 14:34:09,505 - root - ERROR => (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(20)

[SQL: INSERT INTO users (name, lastname, phone, email, password, address, ischild, parent) VALUES (%(name)s, %(lastname)s, %(phone)s, %(email)s, %(password)s, %(address)s, %(ischild)s, %(parent)s) RETURNING users.id]
[parameters: {'name': 'alfredo', 'lastname': 'pacheco', 'phone': '3209345420', 'email': 'laps1308+01@gmail.com', 'password': 'Yenifer-101291', 'address': 'calle 7 #  55-108', 'ischild': False, 'parent': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(20)

[SQL: INSERT INTO users (name, lastname, phone, email, password, address, ischild, parent) VALUES (%(name)s, %(lastname)s, %(phone)s, %(email)s, %(password)s, %(address)s, %(ischild)s, %(parent)s) RETURNING users.id]
[parameters: {'name': 'alfredo', 'lastname': 'pacheco', 'phone': '3209345420', 'email': 'laps1308+01@gmail.com', 'password': 'Yenifer-101291', 'address': 'calle 7 #  55-108', 'ischild': False, 'parent': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2025-06-22 14:34:09,505 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:34:09] "[35m[1mPOST /api/v1/auth/register HTTP/1.1[0m" 500 -
2025-06-22 14:34:55,806 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:34:55] "OPTIONS /api/v1/auth/register HTTP/1.1" 200 -
2025-06-22 14:34:55,834 - root - ERROR => (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(20)

[SQL: INSERT INTO users (name, lastname, phone, email, password, address, ischild, parent) VALUES (%(name)s, %(lastname)s, %(phone)s, %(email)s, %(password)s, %(address)s, %(ischild)s, %(parent)s) RETURNING users.id]
[parameters: {'name': 'alfredo', 'lastname': 'pacheco', 'phone': '3209345420', 'email': 'laps1308+01@gmail.com', 'password': 'Yenifer-101291', 'address': 'calle 7 #  55-108', 'ischild': False, 'parent': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(20)

[SQL: INSERT INTO users (name, lastname, phone, email, password, address, ischild, parent) VALUES (%(name)s, %(lastname)s, %(phone)s, %(email)s, %(password)s, %(address)s, %(ischild)s, %(parent)s) RETURNING users.id]
[parameters: {'name': 'alfredo', 'lastname': 'pacheco', 'phone': '3209345420', 'email': 'laps1308+01@gmail.com', 'password': 'Yenifer-101291', 'address': 'calle 7 #  55-108', 'ischild': False, 'parent': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2025-06-22 14:34:55,834 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:34:55] "[35m[1mPOST /api/v1/auth/register HTTP/1.1[0m" 500 -
2025-06-22 14:34:59,213 - root - ERROR => (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(20)

[SQL: INSERT INTO users (name, lastname, phone, email, password, address, ischild, parent) VALUES (%(name)s, %(lastname)s, %(phone)s, %(email)s, %(password)s, %(address)s, %(ischild)s, %(parent)s) RETURNING users.id]
[parameters: {'name': 'alfredo', 'lastname': 'pacheco', 'phone': '3209345420', 'email': 'laps1308+01@gmail.com', 'password': 'Yenifer-101291', 'address': 'calle 7 #  55-108', 'ischild': False, 'parent': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(20)

[SQL: INSERT INTO users (name, lastname, phone, email, password, address, ischild, parent) VALUES (%(name)s, %(lastname)s, %(phone)s, %(email)s, %(password)s, %(address)s, %(ischild)s, %(parent)s) RETURNING users.id]
[parameters: {'name': 'alfredo', 'lastname': 'pacheco', 'phone': '3209345420', 'email': 'laps1308+01@gmail.com', 'password': 'Yenifer-101291', 'address': 'calle 7 #  55-108', 'ischild': False, 'parent': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2025-06-22 14:34:59,213 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 14:34:59] "[35m[1mPOST /api/v1/auth/register HTTP/1.1[0m" 500 -
2025-06-22 15:15:01,801 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 15:15:01] "OPTIONS /api/v1/auth/register HTTP/1.1" 200 -
2025-06-22 15:15:01,839 - root - ERROR => register() takes 0 positional arguments but 2 were given
register() takes 0 positional arguments but 2 were given
2025-06-22 15:15:01,839 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 15:15:01] "[35m[1mPOST /api/v1/auth/register HTTP/1.1[0m" 500 -
2025-06-22 15:16:36,155 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 15:16:36] "OPTIONS /api/v1/auth/register HTTP/1.1" 200 -
2025-06-22 15:16:36,183 - root - ERROR => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "users_phone_key"
DETAIL:  Key (phone)=(3209345420) already exists.

[SQL: INSERT INTO users (name, lastname, phone, email, password, address, ischild, parent) VALUES (%(name)s, %(lastname)s, %(phone)s, %(email)s, %(password)s, %(address)s, %(ischild)s, %(parent)s) RETURNING users.id]
[parameters: {'name': 'alfredo', 'lastname': 'pacheco', 'phone': '3209345420', 'email': 'laps1308+01@gmail.com', 'password': 'Yenifer-101291', 'address': 'calle 7 #  55-108', 'ischild': False, 'parent': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "users_phone_key"
DETAIL:  Key (phone)=(3209345420) already exists.

[SQL: INSERT INTO users (name, lastname, phone, email, password, address, ischild, parent) VALUES (%(name)s, %(lastname)s, %(phone)s, %(email)s, %(password)s, %(address)s, %(ischild)s, %(parent)s) RETURNING users.id]
[parameters: {'name': 'alfredo', 'lastname': 'pacheco', 'phone': '3209345420', 'email': 'laps1308+01@gmail.com', 'password': 'Yenifer-101291', 'address': 'calle 7 #  55-108', 'ischild': False, 'parent': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-22 15:16:36,183 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 15:16:36] "[35m[1mPOST /api/v1/auth/register HTTP/1.1[0m" 500 -
2025-06-22 15:22:14,254 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/routes/auth.py', reloading
2025-06-22 16:54:42,568 - root - ERROR => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "users_phone_key"
DETAIL:  Key (phone)=(3209345419) already exists.

[SQL: INSERT INTO users (name, lastname, phone, email, password, address, ischild, parent) VALUES (%(name)s, %(lastname)s, %(phone)s, %(email)s, %(password)s, %(address)s, %(ischild)s, %(parent)s) RETURNING users.id]
[parameters: {'name': '', 'lastname': 'luis', 'phone': '3209345419', 'email': 'laps1308@gmail.com', 'password': 'gAAAAABoWHuiQ6rlKBNbfSm9mBbkrcPQnbwH1BXVBKjvkUxQ3dWBsDL948bWhGBpkBDeaeQs9AHxw8ZHSuglyOGWrTwyfQ0SJg==', 'address': 'calle 7 # 55-109', 'ischild': False, 'parent': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "users_phone_key"
DETAIL:  Key (phone)=(3209345419) already exists.

[SQL: INSERT INTO users (name, lastname, phone, email, password, address, ischild, parent) VALUES (%(name)s, %(lastname)s, %(phone)s, %(email)s, %(password)s, %(address)s, %(ischild)s, %(parent)s) RETURNING users.id]
[parameters: {'name': '', 'lastname': 'luis', 'phone': '3209345419', 'email': 'laps1308@gmail.com', 'password': 'gAAAAABoWHuiQ6rlKBNbfSm9mBbkrcPQnbwH1BXVBKjvkUxQ3dWBsDL948bWhGBpkBDeaeQs9AHxw8ZHSuglyOGWrTwyfQ0SJg==', 'address': 'calle 7 # 55-109', 'ischild': False, 'parent': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-22 16:54:42,569 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 16:54:42] "[35m[1mPOST /api/v1/auth/register HTTP/1.1[0m" 500 -
2025-06-22 16:54:59,197 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 16:54:59] "OPTIONS /api/v1/auth/register HTTP/1.1" 200 -
2025-06-22 16:54:59,668 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 16:54:59] "[32mPOST /api/v1/auth/register HTTP/1.1[0m" 301 -
2025-06-22 16:57:22,889 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/app.py', reloading
2025-06-22 17:50:08,544 - root - ERROR => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "users_phone_key"
DETAIL:  Key (phone)=(3209345419) already exists.

[SQL: INSERT INTO users (name, lastname, phone, email, password, address, ischild, parent) VALUES (%(name)s, %(lastname)s, %(phone)s, %(email)s, %(password)s, %(address)s, %(ischild)s, %(parent)s) RETURNING users.id]
[parameters: {'name': '', 'lastname': 'luis', 'phone': '3209345419', 'email': 'laps1308@gmail.com', 'password': 'gAAAAABoWIigLh3NhN1vwDDGQTbK4MP1I8PFZvQ_nZvFJPKHUXtjs-1i2tBvNQAwAY5Dj20gFeXH5iyfBsr5LPIl7loViPPsYw==', 'address': 'calle 7 # 55-109', 'ischild': False, 'parent': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "users_phone_key"
DETAIL:  Key (phone)=(3209345419) already exists.

[SQL: INSERT INTO users (name, lastname, phone, email, password, address, ischild, parent) VALUES (%(name)s, %(lastname)s, %(phone)s, %(email)s, %(password)s, %(address)s, %(ischild)s, %(parent)s) RETURNING users.id]
[parameters: {'name': '', 'lastname': 'luis', 'phone': '3209345419', 'email': 'laps1308@gmail.com', 'password': 'gAAAAABoWIigLh3NhN1vwDDGQTbK4MP1I8PFZvQ_nZvFJPKHUXtjs-1i2tBvNQAwAY5Dj20gFeXH5iyfBsr5LPIl7loViPPsYw==', 'address': 'calle 7 # 55-109', 'ischild': False, 'parent': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-22 17:50:08,544 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:50:08] "[35m[1mPOST /api/v1/auth/register HTTP/1.1[0m" 500 -
2025-06-22 17:50:24,024 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:50:24] "OPTIONS /api/v1/auth/register HTTP/1.1" 200 -
2025-06-22 17:50:24,478 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:50:24] "[32mPOST /api/v1/auth/register HTTP/1.1[0m" 301 -
2025-06-22 17:51:55,901 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:51:55] "OPTIONS /api/v1/plan HTTP/1.1" 200 -
2025-06-22 17:51:55,912 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:51:55] "GET /api/v1/plan HTTP/1.1" 200 -
2025-06-22 17:52:03,783 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:52:03] "OPTIONS /api/v1/plan HTTP/1.1" 200 -
2025-06-22 17:52:03,795 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:52:03] "GET /api/v1/plan HTTP/1.1" 200 -
2025-06-22 17:52:34,907 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:52:34] "OPTIONS /api/v1/auth/register HTTP/1.1" 200 -
2025-06-22 17:52:35,378 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:52:35] "[32mPOST /api/v1/auth/register HTTP/1.1[0m" 301 -
2025-06-22 17:56:14,585 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:56:14] "OPTIONS /api/v1/plan HTTP/1.1" 200 -
2025-06-22 17:56:14,600 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:56:14] "GET /api/v1/plan HTTP/1.1" 200 -
2025-06-22 17:56:36,221 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:56:36] "OPTIONS /api/v1/auth/register HTTP/1.1" 200 -
2025-06-22 17:56:36,686 - werkzeug - INFO => 127.0.0.1 - - [22/Jun/2025 17:56:36] "[32mPOST /api/v1/auth/register HTTP/1.1[0m" 301 -
2025-06-22 17:59:45,437 - werkzeug - INFO =>  * Detected change in '/home/luis/Proyectos/agdt-b/src/routes/auth.py', reloading
